# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'huchagrafica.ui'
#
# Created: Fri Dec  2 12:46:08 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Hucha(object):
    def setupUi(self, Hucha):
        Hucha.setObjectName(_fromUtf8("Hucha"))
        Hucha.resize(800, 600)
        Hucha.setWindowTitle(QtGui.QApplication.translate("Hucha", "Hucha", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(Hucha)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.combo_Tipo = QtGui.QComboBox(self.centralwidget)
        self.combo_Tipo.setGeometry(QtCore.QRect(170, 20, 111, 29))
        self.combo_Tipo.setObjectName(_fromUtf8("combo_Tipo"))
        self.combo_Tipo.addItem(_fromUtf8(""))
        self.combo_Tipo.setItemText(0, QtGui.QApplication.translate("Hucha", "Ingreso", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_Tipo.addItem(_fromUtf8(""))
        self.combo_Tipo.setItemText(1, QtGui.QApplication.translate("Hucha", "Gasto", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_Lugar = QtGui.QComboBox(self.centralwidget)
        self.combo_Lugar.setGeometry(QtCore.QRect(430, 20, 111, 29))
        self.combo_Lugar.setObjectName(_fromUtf8("combo_Lugar"))
        self.combo_Lugar.addItem(_fromUtf8(""))
        self.combo_Lugar.setItemText(0, QtGui.QApplication.translate("Hucha", "Banco", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_Lugar.addItem(_fromUtf8(""))
        self.combo_Lugar.setItemText(1, QtGui.QApplication.translate("Hucha", "Hucha", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 74, 110, 29))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 41, 30))
        self.label.setText(QtGui.QApplication.translate("Hucha", "Tipo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 20, 51, 30))
        self.label_2.setText(QtGui.QApplication.translate("Hucha", "Lugar:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 74, 50, 30))
        self.label_3.setText(QtGui.QApplication.translate("Hucha", "Fecha:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 130, 90, 30))
        self.label_4.setText(QtGui.QApplication.translate("Hucha", "Comentarios:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.boton_Ok = QtGui.QPushButton(self.centralwidget)
        self.boton_Ok.setGeometry(QtCore.QRect(600, 120, 41, 41))
        self.boton_Ok.setToolTip(QtGui.QApplication.translate("Hucha", "Ingresar nuevo movimiento", None, QtGui.QApplication.UnicodeUTF8))
        self.boton_Ok.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/icons/Faenza/actions/32/dialog-ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Ok.setIcon(icon)
        self.boton_Ok.setIconSize(QtCore.QSize(32, 32))
        self.boton_Ok.setObjectName(_fromUtf8("boton_Ok"))
        self.text_Cantidad = QtGui.QTextEdit(self.centralwidget)
        self.text_Cantidad.setGeometry(QtCore.QRect(430, 74, 111, 31))
        self.text_Cantidad.setObjectName(_fromUtf8("text_Cantidad"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 80, 67, 21))
        self.label_5.setText(QtGui.QApplication.translate("Hucha", "Cantidad:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.text_Comentarios = QtGui.QTextEdit(self.centralwidget)
        self.text_Comentarios.setGeometry(QtCore.QRect(170, 130, 411, 31))
        self.text_Comentarios.setObjectName(_fromUtf8("text_Comentarios"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(580, 10, 181, 101))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 0, 51, 30))
        self.label_6.setText(QtGui.QApplication.translate("Hucha", "Hucha:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 51, 30))
        self.label_8.setText(QtGui.QApplication.translate("Hucha", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_Total = QtGui.QLabel(self.groupBox)
        self.label_Total.setGeometry(QtCore.QRect(100, 60, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Total.setFont(font)
        self.label_Total.setText(QtGui.QApplication.translate("Hucha", "0 €", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Total.setObjectName(_fromUtf8("label_Total"))
        self.label_Banco = QtGui.QLabel(self.groupBox)
        self.label_Banco.setGeometry(QtCore.QRect(100, 30, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Banco.setFont(font)
        self.label_Banco.setText(QtGui.QApplication.translate("Hucha", "0 €", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Banco.setObjectName(_fromUtf8("label_Banco"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 51, 30))
        self.label_7.setText(QtGui.QApplication.translate("Hucha", "Banco:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_Hucha = QtGui.QLabel(self.groupBox)
        self.label_Hucha.setGeometry(QtCore.QRect(100, 0, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Hucha.setFont(font)
        self.label_Hucha.setText(QtGui.QApplication.translate("Hucha", "0 €", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Hucha.setObjectName(_fromUtf8("label_Hucha"))
        self.boton_Cancelar = QtGui.QPushButton(self.centralwidget)
        self.boton_Cancelar.setEnabled(False)
        self.boton_Cancelar.setGeometry(QtCore.QRect(670, 120, 41, 41))
        self.boton_Cancelar.setToolTip(QtGui.QApplication.translate("Hucha", "Cancelar edicion", None, QtGui.QApplication.UnicodeUTF8))
        self.boton_Cancelar.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/icons/Faenza/actions/24/process-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Cancelar.setIcon(icon1)
        self.boton_Cancelar.setObjectName(_fromUtf8("boton_Cancelar"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 170, 771, 411))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 741, 301))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Hucha", "Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Hucha", "Lugar", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Hucha", "Comentarios", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Hucha", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("Hucha", "Cantidad", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.boton_Editar = QtGui.QPushButton(self.tab)
        self.boton_Editar.setGeometry(QtCore.QRect(70, 320, 41, 41))
        self.boton_Editar.setToolTip(QtGui.QApplication.translate("Hucha", "Editar la entrada seleccionada (seleccione la fila completa)", None, QtGui.QApplication.UnicodeUTF8))
        self.boton_Editar.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/icons/Faenza/actions/24/gtk-edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Editar.setIcon(icon2)
        self.boton_Editar.setObjectName(_fromUtf8("boton_Editar"))
        self.boton_Borrar = QtGui.QPushButton(self.tab)
        self.boton_Borrar.setGeometry(QtCore.QRect(10, 320, 41, 41))
        self.boton_Borrar.setToolTip(QtGui.QApplication.translate("Hucha", "Borrar la fila seleccionada (selecciones la fila completa)", None, QtGui.QApplication.UnicodeUTF8))
        self.boton_Borrar.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/icons/Faenza/actions/24/editdelete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Borrar.setIcon(icon3)
        self.boton_Borrar.setIconSize(QtCore.QSize(24, 24))
        self.boton_Borrar.setObjectName(_fromUtf8("boton_Borrar"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.mpl = MplWidget(self.tab_2)
        self.mpl.setGeometry(QtCore.QRect(10, 10, 741, 301))
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.boton_Hucha = QtGui.QPushButton(self.tab_2)
        self.boton_Hucha.setGeometry(QtCore.QRect(20, 320, 99, 29))
        self.boton_Hucha.setText(QtGui.QApplication.translate("Hucha", "Hucha", None, QtGui.QApplication.UnicodeUTF8))
        self.boton_Hucha.setObjectName(_fromUtf8("boton_Hucha"))
        self.boton_Banco = QtGui.QPushButton(self.tab_2)
        self.boton_Banco.setGeometry(QtCore.QRect(140, 320, 99, 29))
        self.boton_Banco.setText(QtGui.QApplication.translate("Hucha", "Banco", None, QtGui.QApplication.UnicodeUTF8))
        self.boton_Banco.setObjectName(_fromUtf8("boton_Banco"))
        self.boton_Total = QtGui.QPushButton(self.tab_2)
        self.boton_Total.setGeometry(QtCore.QRect(260, 320, 99, 29))
        self.boton_Total.setText(QtGui.QApplication.translate("Hucha", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.boton_Total.setObjectName(_fromUtf8("boton_Total"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.boton_Nuevo = QtGui.QPushButton(self.centralwidget)
        self.boton_Nuevo.setGeometry(QtCore.QRect(10, 20, 51, 51))
        self.boton_Nuevo.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/icons/Faenza/actions/48/stock_new-text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Nuevo.setIcon(icon4)
        self.boton_Nuevo.setIconSize(QtCore.QSize(48, 48))
        self.boton_Nuevo.setObjectName(_fromUtf8("boton_Nuevo"))
        self.boton_Abrir = QtGui.QPushButton(self.centralwidget)
        self.boton_Abrir.setGeometry(QtCore.QRect(10, 90, 51, 51))
        self.boton_Abrir.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/icons/Faenza/actions/48/fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_Abrir.setIcon(icon5)
        self.boton_Abrir.setIconSize(QtCore.QSize(48, 48))
        self.boton_Abrir.setObjectName(_fromUtf8("boton_Abrir"))
        Hucha.setCentralWidget(self.centralwidget)

        self.retranslateUi(Hucha)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Hucha)

    def retranslateUi(self, Hucha):
        item = self.tableWidget.horizontalHeaderItem(0)
        item = self.tableWidget.horizontalHeaderItem(1)
        item = self.tableWidget.horizontalHeaderItem(2)
        item = self.tableWidget.horizontalHeaderItem(3)
        item = self.tableWidget.horizontalHeaderItem(4)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Hucha", "Tabla", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Hucha", "Grafica", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
